
version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgresql-db:/var/lib/postgresql/data
      - ./.infrastructure/postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgresql-db: