version: '3.9'

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./postgres_setup.sql:/docker-entrypoint-initdb.d/postgres_setup.sql
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres-db: